# Cython tutorial notebook

In this notebook we will test the usage of every Cython script included in the tutorial

In [1]:
import numpy as np

## 1. Hello, world!

You can build and install this simple Cython method with:

`$ python setup_hello.pyx build_ext --inplace`

or, alternatively, you can execute the Makefile script that builds and installs all scripts

`$ make all`

In [2]:
from hello_world import print_hello_name

In [3]:
print_hello_name("world")

Hello,  world !


## 2. Array operations

You can build and install these Cython methods with:

`$ python setup_arrays.pyx build_ext --inplace`

In [4]:
import array_operations

In [5]:
def test_sum_of_two_arrays():
    n_rows = 10
    n_cols = 10
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    C = array_operations.sum_matrices(A, B)
    print(C)
    return

test_sum_of_two_arrays()

[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


In [6]:
def time_the_sum_of_two_arrays():
    n_rows = 1000
    n_cols = 1000
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    %timeit array_operations.sum_matrices(A, B)
    %timeit A + B
    return

time_the_sum_of_two_arrays()

61.2 ms ± 376 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
605 µs ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


The time result is not very impressive because Numpy is specially tuned to do computations like this.