# Cython tutorial notebook

In this notebook we will test the usage of every Cython script included in the tutorial

In [1]:
import numpy as np

## 1. Hello, world!

You can build and install this simple Cython method with:

`$ python setup_hello.pyx build_ext --inplace`

or, alternatively, you can execute the Makefile script that builds and installs all scripts

`$ make all`

In [2]:
from hello_world import print_hello_name

In [3]:
print_hello_name("world")

Hello,  world !


## 2. Array operations

You can build and install these Cython methods with:

`$ python setup_arrays.pyx build_ext --inplace`

In [4]:
import array_operations

In [5]:
def test_sum_of_two_arrays():
    n_rows = 10
    n_cols = 10
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    C = array_operations.sum_matrices(A, B)
    print(C)
    return

test_sum_of_two_arrays()

[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


In [6]:
def time_the_sum_of_two_arrays():
    n_rows = 1000
    n_cols = 1000
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    %time array_operations.sum_matrices(A, B)
    %time A + B
    return

time_the_sum_of_two_arrays()

CPU times: user 69.7 ms, sys: 0 ns, total: 69.7 ms
Wall time: 69.4 ms
CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 1.7 ms


The time result is not very impressive because Numpy is specially tuned to do computations like this.

In [10]:
def test_complex_array_operation():
    n = 100
    rng_seed = 123321
    rng = np.random.default_rng(rng_seed)
    a = rng.random(n)
    b = rng.random(n)

    out_cython = array_operations.do_complex_array_operation(a, b)
    out_numpy = np.sum( np.cos(a + 2 * b) + np.maximum(a**2, b) )

    print(f'Cython result: {out_cython}')
    print(f'Numpy  result: {out_numpy}')

    print('Time Cython:')
    %time array_operations.do_complex_array_operation(a, b)
    print('Time Numpy :')
    %time np.sum( np.cos(a + 2 * b) + np.maximum(a**2, b) )

    return

test_complex_array_operation()

Cython result: 65.99609511241533
Numpy  result: 65.99609511241533
Time Cython:
CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 11.7 µs
Time Numpy :
CPU times: user 45 µs, sys: 0 ns, total: 45 µs
Wall time: 46 µs
