# Cython tutorial notebook

In this notebook we will test the usage of every Cython script included in the tutorial

In [1]:
import numpy as np

## 1. Hello, world!

You can build and install this simple Cython method with:

`$ python setup_hello.pyx build_ext --inplace`

or, alternatively, you can execute the Makefile script that builds and installs all scripts

`$ make all`

In [2]:
from hello_world import print_hello_name

In [3]:
print_hello_name("world")

Hello,  world !


## 2. Array operations

You can build and install these Cython methods with:

`$ python setup_arrays.pyx build_ext --inplace`

In [4]:
import array_operations

In [5]:
def test_sum_of_two_arrays():
    n_rows = 10
    n_cols = 10
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    C = array_operations.sum_matrices(A, B)
    print(C)
    return

test_sum_of_two_arrays()

[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


In [6]:
def time_the_sum_of_two_arrays():
    n_rows = 1000
    n_cols = 1000
    shape = (n_rows, n_cols)
    A = np.full(shape, 1.0)
    B = np.full(shape, 2.0)
    %time array_operations.sum_matrices(A, B)
    %time A + B
    return

time_the_sum_of_two_arrays()

CPU times: user 118 ms, sys: 251 µs, total: 118 ms
Wall time: 118 ms
CPU times: user 7.17 ms, sys: 0 ns, total: 7.17 ms
Wall time: 6.92 ms


The time result is not very impressive because Numpy is specially tuned to do computations like this.

In [7]:
def test_complex_array_operation():
    n = 100
    rng_seed = 123321
    rng = np.random.default_rng(rng_seed)
    a = rng.random(n)
    b = rng.random(n)

    out_cython = array_operations.do_complex_array_operation(a, b)
    out_numpy = np.sum( np.cos(a + 2 * b) + np.maximum(a**2, b) )

    print(f'Cython result: {out_cython}')
    print(f'Numpy  result: {out_numpy}')

    print('Time Cython:')
    %time array_operations.do_complex_array_operation(a, b)
    print('Time Numpy :')
    %time np.sum( np.cos(a + 2 * b) + np.maximum(a**2, b) )

    return

test_complex_array_operation()

Cython result: 65.99609511241533
Numpy  result: 65.99609511241533
Time Cython:
CPU times: user 11 µs, sys: 3 µs, total: 14 µs
Wall time: 18.6 µs
Time Numpy :
CPU times: user 40 µs, sys: 13 µs, total: 53 µs
Wall time: 55.1 µs


## 3. Random number generator 

This script computes Pi using Monte Carlo

To compile, run:
`$ python setup_monte_carlo.pyx build_ext --inplace`

In [8]:
import monte_carlo

In [9]:
def test_monte_carlo(n_samples):
    # Make the equivalent method with Numpy.
    def compute_pi_with_numpy(n):
        rng = np.random.default_rng()
        x = rng.random(n)
        y = rng.random(n)
        counts = np.count_nonzero( x ** 2 + y ** 2 <= 1)
        pi = 4 * counts / n
        return pi

    pi_cython = monte_carlo.compute_pi_using_monte_carlo(n_samples)
    pi_numpy = compute_pi_with_numpy(n_samples)
    print(f"Pi with Cython: {pi_cython}")
    print(f"Pi with Numpy : {pi_numpy}")

    print('Time Cython:')
    %time monte_carlo.compute_pi_using_monte_carlo(n_samples)
    print('Time Numpy :')
    %time compute_pi_with_numpy(n_samples)

    return

test_monte_carlo(1000000)

Pi with Cython: 3.142636
Pi with Numpy : 3.141464
Time Cython:
CPU times: user 102 ms, sys: 1.05 ms, total: 103 ms
Wall time: 102 ms
Time Numpy :
CPU times: user 12.8 ms, sys: 10.7 ms, total: 23.5 ms
Wall time: 23.5 ms


Here we observe than Numpy's vector operations are super efficient at this method